development:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: :plain
  :user_name: <%= ENV['MANDRILL_USERNAME'] %>
  :password: <%= ENV['MANDRILL_APIKEY'] %>
  :domain: www.filmlovers.co.uk
  :enable_starttls_auto: true
staging:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: :plain
  :user_name: <%= ENV['MANDRILL_USERNAME'] %>
  :password: <%= ENV['MANDRILL_APIKEY'] %>
  :domain: www.filmlovers.co.uk
  :enable_starttls_auto: true
production:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: :plain
  :user_name: <%= ENV['MANDRILL_USERNAME'] %>
  :password: <%= ENV['MANDRILL_APIKEY'] %>
  :domain: www.filmlovers.co.uk
  :enable_starttls_auto: true
digitalocean:
  :address: smtp.mandrillapp.com
  :port: 587
  :authentication: :plain
  :user_name: <%= ENV['MANDRILL_USERNAME'] %>
  :password: <%= ENV['MANDRILL_APIKEY'] %>
  :domain: www.filmlovers.co.uk
  :enable_starttls_auto: true


