development:
  key: 'b14b8fd215a745572dc0510e8cddfee4'
  namespace: 'filmlovers-development'
  api: "http://api.themoviedb.org/3/"
production:
  key: 'b14b8fd215a745572dc0510e8cddfee4'
  namespace: 'filmlovers-development'
  api: "http://api.themoviedb.org/3/"